### ISSUE TITLE
Error: Undefined function 'smooth' for input arguments of type 'double'.

### ISSUE THREAD

**Issue by cvaaga** [DeNardoLab/BehaviorDEPOT#1]
First off, this program looks amazing. However, when I try to it on my data, I am getting an the error: 

'Undefined function 'smooth' for input arguments of type 'double'.

Error in smoothTracking_custom (line 23)
        x = smooth(ux, smoothSpan, smoothMethod);

Error in BehDepo_mainscript_single (line 54)
   Tracking = smoothTracking_custom(Tracking, Params);

Error in BehDep_GUI_v051/StartButtonPushed (line 131)
                BehDepo_mainscript_single(app.P)
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.`

Any recommendations on how to avoid this error?

Thanks in advance!

**Comment by cjgabrie** [comment]
Hello! Thanks for testing out the software and reporting on this issue. The problem is that the smoothing function currently used by BehaviorDEPOT comes from the Curve Fitting Toolbox, which appears to not be installed on your machine.

You probably didn't have it installed because it was missing from our dependencies guide--this is now updated on the ReadMe. If you install the toolbox, the error should resolve itself.

Thanks for helping us catch these early issues!
