### ISSUE TITLE
Problems with smoothing keypoint tracking data

### ISSUE THREAD

**Issue by NuriaCA** [DeNardoLab/BehaviorDEPOT#12]
Hi!
I’m working on detecting freezing in several conditions and luckily found your software. Thanks for making BehaviorDepot open source :)
 
I am running BehaviorDepot v1.3c on Matlab 2022a on Windows10.

I’m struggling with the part of the analysis that smoothes and corrects keypoint tracking data. It is giving me poor pose-estimation data. To see if I am using the tool correctly, I have a few questions: 
1.	In general, do you recommend using the default parameters (except for distance calibration, which needs to be calculated) – i.e. tracking cutoff threshold 0.1, smoothing span 14, Hampel span 7- or modifying them depending on the data?
2.	Is it normal that data with a likelihood >0.9 (even 1) change so much after smoothing?
3.	What does BehaviourDepot do when a body part is hidden in DLC (with an associated likelihood close to 0)? E.g. This is very frequent for the nose in mice, but in my case, BehaviourDepot is estimating a position which doesn’t match reality or DLC estimation.

Thanks a lot!
![Imagen1](https://user-images.githubusercontent.com/115792773/196167298-c3389f5f-7a4c-43b8-96e8-ddd01cd55992.png)
![Imagen2](https://user-images.githubusercontent.com/115792773/196167309-bc8030a7-5af1-4776-8caf-ae0c1cfe559e.png)

**Comment by cjgabrie** [comment]
Hello! Thanks for giving BehaviorDEPOT a try!

Sorry to not address these questions sooner--this issue escaped my notice until now.

"1) In general, do you recommend using the default parameters (except for distance calibration, which needs to be calculated) – i.e. tracking cutoff threshold 0.1, smoothing span 14, Hampel span 7- or modifying them depending on the data?"

- In our experience, these smoothing parameters work fairly well across different datasets, but there are multiple factors to consider, and it's definitely worth trying to adjust the parameters if you aren't getting high quality data.
- I would be sure that DLC has been trained enough to work consistently. It will never be perfect, but the smoothing performance will suffer if it's not right the majority of the time
- Some users have reported significantly improved data by turning off the Hampel correction (which removes outliers)
- Smoothing span is the window of time a smoothing algorithm will look at (in frames). Since the amount of movement captured between frames is based on framerate, it will likely need to be adjusted when using different FPS (span of 14 came from data at 30-50fps)
- Tracking cutoff threshold controls how much data is being tossed from the original DLC (based on the likelihood score). The default 0.1 takes a very conservative approach to removing data, only tossing values BELOW 0.1. You might try raising this threshold to slice off more of the incorrect DLC data and thus improve smoothing integrity
- We also use a default smoothing algorithm of LOWESS; you can try using different methods to see if they work better on your data (BD uses the smooth() function in Matlab, which is detailed here: https://www.mathworks.com/help/curvefit/smooth.html#mw_ad6b65fd-4dac-46c4-a649-a7a0b301eb80)

"2) Is it normal that data with a likelihood >0.9 (even 1) change so much after smoothing?"
- It's not normal for good data to move to bad spots, but it can happen based on how smoothing works. If your dataset includes poor tracking data during smoothing (e.g. from not having a high enough cutoff threshold), then that poor data will influence the good data. You can try to avoid this by: a) adjusting cutoff threshold; b) retraining DLC network; c) reducing smoothing span; or d) changing smoothing method.

"3) What does BehaviourDepot do when a body part is hidden in DLC (with an associated likelihood close to 0)? E.g. This is very frequent for the nose in mice, but in my case, BehaviourDepot is estimating a position which doesn’t match reality or DLC estimation."
- BehaviorDEPOT attempts to interpolate all missing and removed data. This will usually produce a close estimate to reality, as interpolation will use the surrounding data (entering the obscured area and exiting the obscured area) to estimate the obscured point. However, this default behavior could be troublesome if certain situations. I might recommend using custom ROIs to mark regions where the points become obscured in order to find when this happens and provide a means of removing the data if desired.

Please let me know if there are other questions I can help with.

Best,
Chris
